//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enrollment
    {
        public int EnrollmentID { get; set; }
        [Required]
        [StringLength(50)]
        public Nullable<decimal> Grade { get; set; }
        [Required]
        [StringLength(50)]
        public int CourseID { get; set; }
        [Required]
        [StringLength(50)]
        public int StudentID { get; set; }
        [Required]
        [StringLength(50)]
        public Nullable<bool> Enabled { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
